use hr_database


SELECT *
FROM EMPLOYEES;

select last_name
from EMPLOYEES
where LAST_NAME='David'

SELECT d.DEPARTMENT_NAME,l.CITY,l.STATE_PROVINCE
FROM DEPARTMENTS d
inner join DEPARTMENTS d on e.DEPARTMENT_ID=d.DEPARTMENT_ID
inner join LOCATIONS l on d.LOCATION_ID=l.LOCATION_ID
where d.LOCATION_ID >1700;

SELECT DEPARTMENT_NAME,CITY,EMPLOYEE_ID
FROM DEPARTMENTS d
INNER JOIN EMPLOYEES e on d.DEPARTMENT_ID=e.DEPARTMENT_ID
inner join LOCATIONS l on d.LOCATION_ID=l.LOCATION_ID
WHERE d.DEPARTMENT_NAME  LIKE 'D%'or d.DEPARTMENT_NAME LIKE '%N';


--'SEARCHED %'; starts with/'% SEARCHED';  -- ends with/'%SEARCHED%';  -- contains